[instrument]
two_theta_min = 10.0
two_theta_max = 120.0
N = 1000
lambda = 1.5418
noise_level = 0.15

[peak_width]
U = 0.0001
V = 0.00005
W = 0.00001
K = 0.9
Epsilon = 0.001
D = 500.0

[lattice]
# Lattice parameters in Angstroms (Å)
[lattice.SC]
Po = 3.352

[lattice.BCC]
# Fe = 2.866
# Mo = 3.142
# W  = 3.155
V  = 3.0399
# Nb = 3.3008
# Ta = 3.3058

[lattice.FCC]
# Al = 4.046
# Ni = 3.499
# Cu = 3.594
# Pd = 3.859
Ag = 4.079
# Pt = 3.912
# Au = 4.065
# Pb = 4.920
